### ISSUE TITLE
Getting a error running spark-submit job

### ISSUE THREAD

**Issue by Jagdish007** [facebookresearch/Horizon#101]
Hello,

I am trying to follow the instructions here: https://github.com/facebookresearch/Horizon/blob/master/docs/usage.md

When I run this script:
/usr/local/spark/bin/spark-submit \
  --class com.facebook.spark.rl.Preprocessor preprocessing/target/rl-preprocessing-1.1.jar \
  "`cat ml/rl/workflow/sample_configs/discrete_action/timeline.json`"

I am getting2019-02-27 00:57:03 INFO  HiveMetaStore:746 - 0: get_database: global_temp
2019-02-27 00:57:03 INFO  audit:371 - ugi=root	ip=unknown-ip-addr	cmd=get_database: global_temp	
2019-02-27 00:57:03 WARN  ObjectStore:568 - Failed to get database global_temp, returning NoSuchObjectException
Exception in thread "main" org.apache.spark.sql.AnalysisException: grouping expressions sequence is empty, and 'source_table.`mdp_id`' is not an aggregate function. Wrap '()' in windowing function(s) or wrap 'source_table.`mdp_id`' in first() (or first_value) if you don't care which value you get.;;
'Sort ['HASH('mdp_id, 'sequence_number) ASC NULLS FIRST], false
+- 'RepartitionByExpression ['HASH('mdp_id, 'sequence_number)], 200
   +- 'Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, next_state_features#24, next_action#25, sequence_number#2, sequence_number_ordinal#26, time_diff#27, possible_actions#7, possible_next_actions#28, metrics#8]
      +- 'Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8, next_state_features#24, next_action#25, sequence_number_ordinal#26, _we3#30, possible_next_actions#28, next_state_features#24, next_action#25, sequence_number_ordinal#26, (coalesce(_we3#30, sequence_number#2) - sequence_number#2) AS time_diff#27, possible_next_actions#28]
         +- 'Window [lead(state_features#4, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS next_state_features#24, lead(action#5, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS next_action#25, row_number() windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS sequence_number_ordinal#26, lead(sequence_number#2, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS _we3#30, lead(possible_actions#7, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS possible_next_actions#28], [mdp_id#1], [mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST]
            +- 'Filter isnotnull('next_state_features)
               +- Aggregate [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8]
                  +- SubqueryAlias `source_table`
                     +- Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8]
                        +- Filter ((ds#0 >= 2019-01-01) && (ds#0 <= 2019-01-01))
                           +- SubqueryAlias `cartpole_discrete`
                              +- Relation[ds#0,mdp_id#1,sequence_number#2,action_probability#3,state_features#4,action#5,reward#6,possible_actions#7,metrics#8] json

I tried the steps, after manually installing Hbase (This step is missing in the documentation. Please let me know, if you want me to add it)

I am using docker on Mac instructions (https://github.com/facebookresearch/Horizon/blob/master/docs/installation.md) to get going. Can anyone please help me on how to move forward?

**Comment by sureshakella** [comment]
+1 confirm the issue happens using docker on Linux as well.

**Comment by Jagdish007** [comment]
I checked it on Linux as well without success.
Do any of you know, if an earlier commit worked?

**Comment by Jagdish007** [comment]
Tried to run it using older version of Spark based on commit https://github.com/facebookresearch/Horizon/commit/38d95ddba7e708a51f626227a8836295db394ee7
wihout success. We are blocked. Appreciate any guidance on how to move forward.

**Comment by MisterTea** [comment]
Hey all,

It does seem that the open source is broken. We are working to fix it and I'm also going to add a jenkins test that does most of the usage so we don't break it again.

**Comment by sureshakella** [comment]
Assuming this is reopened because the issue still exists. I don't see initial error but a different error now.

`Exception in thread "main" org.apache.spark.sql.AnalysisException: grouping expressions sequence is empty, and 'source_table.`mdp_id`' is not an aggregate function. Wrap '()' in windowing function(s) or wrap 'source_table.`mdp_id`' in first() (or first_value) if you don't care which value you get.;;
'Sort ['HASH('mdp_id, 'sequence_number) ASC NULLS FIRST], false

+- 'RepartitionByExpression ['HASH('mdp_id, 'sequence_number)], 200
   +- 'Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, next_state_features#76, next_action#77, sequence_number#2, sequence_number_ordinal#78, time_diff#79, possible_actions#7, possible_next_actions#80, metrics#8]

      +- 'Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8, next_state_features#76, next_action#77, sequence_number_ordinal#78, _we3#82, possible_next_actions#80, next_state_features#76, next_action#77, sequence_number_ordinal#78, (coalesce(_we3#82, sequence_number#2) - sequence_number#2) AS time_diff#79, possible_next_actions#80]

         +- 'Window [lead(state_features#4, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS next_state_features#76, lead(action#5, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS next_action#77, row_number() windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS sequence_number_ordinal#78, lead(sequence_number#2, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS _we3#82, lead(possible_actions#7, 1, null) windowspecdefinition(mdp_id#1, mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST, specifiedwindowframe(RowFrame, 1, 1)) AS possible_next_actions#80], [mdp_id#1], [mdp_id#1 ASC NULLS FIRST, sequence_number#2 ASC NULLS FIRST]

            +- 'Filter isnotnull('next_state_features)
               +- Aggregate [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8]
                  +- SubqueryAlias `source_table`
                     +- Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, sequence_number#2, possible_actions#7, metrics#8]
                        +- Filter ((ds#0 >= 2019-01-01) && (ds#0 <= 2019-01-01))
                           +- SubqueryAlias `cartpole_discrete`
                              +- 

Relation[ds#0,mdp_id#1,sequence_number#2,action_probability#3,state_features#4,action#5,reward#6,possible_actions#7,metrics#8] json`

**Comment by MisterTea** [comment]
@sureshakella That's a bug in spark 2.4.0.  Downgrade to 2.3.3 to fix.  You don't need to change the library, but just install the 2.3.3 version of the spark engine.

**Comment by sureshakella** [comment]
Thank you. Will try and update you.

**Comment by Jagdish007** [comment]
Tried spark-2.3.3-bin-hadoop2.7, spark-2.3.3-bin-hadoop2.6, reusing the setup that was created without success. Do you have any recommendation? 

@sureshakella Please let me know, if it worked for you.

**Comment by sureshakella** [comment]
It din't work for me either. Though it spit a different exception this time

Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'coalesce(`next_state_features`, UDF())' due to data type mismatch: input to function coalesce should all be the same type, but it's [map<string,double>, map<bigint,double>];;

'Project [mdp_id#1, state_features#4, action#5, action_probability#3, reward#6, coalesce(next_state_features#80, UDF()) AS next_state_features#100, next_action#81, sequence_number#2, sequence_number_ordinal#82, time_diff#83, possible_actions#7, possible_next_actions#84, metrics#8]

**Comment by MisterTea** [comment]
With the changes in https://github.com/facebookresearch/Horizon/pull/104 and using spark 2.3.3 I was able to go through the whole usage doc.

**Comment by sureshakella** [comment]
Awesome. Thank you. Giving it a try. Will update soon.

**Comment by Jagdish007** [comment]
Thanks @MisterTea .

For the benefit of the community, here is what worked for me.

1) Apply the pull request #104 or checkout a new repo with the pull request
2) Follow the docker steps from /instalation.md
3) Execute all the steps in /installation.ms and usage.md
4) Before running the spark job in usage.md,  get spark-2.3.3-bin-hadoop2.7 and replace the spark lib using following steps:
wget https://archive.apache.org/dist/spark/spark-2.3.3/spark-2.3.3-bin-hadoop2.7.tgz
tar -xzf spark-2.3.3-bin-hadoop2.7.tgz
sudo mv spark-2.3.3-bin-hadoop2.7 /usr/local/spark
5)Run next steps in usage.md.

**Comment by MisterTea** [comment]
For reference, #104 includes a change to installation.md to use 2.3.3 so once that lands (in about an hour) you shouldn't have to do anything special
