### ISSUE TITLE
Incorrect possible_actions for cartpole example

### ISSUE THREAD

**Issue by martin-benson** [facebookresearch/Horizon#106]
Hi,

I tried running the offline example in usage.md and spotted something that looks funny to me. I ran the spark job to preprocess the training data and looked at the first entry in the resulting json file. The values for possible_actions and possible_next_actions look weird to me - I'd have expected ["0", "1"] but instead it's [1,1] (see below). This is true over the whole file too. Am I misunderstanding something?

Thanks,

Martin.

{
    "mdp_id": "129",
    "sequence_number": 107,
    "propensity": 0.95,
    "state_features": {
        "0": 0.9470082572631731,
        "1": 1.2941002415409237,
        "2": 0.11945455504963116,
        "3": -0.24271752599511354
    },
    "action": 1,
    "reward": 1.0,
    "next_state_features": {
        "0": 0.9728902620939915,
        "1": 1.4873313444805643,
        "2": 0.1146002045297289,
        "3": -0.495462494594765
    },
    "time_diff": 1,
    "possible_actions": [
        1,
        1
    ],
    "possible_next_actions": [
        1,
        1
    ],
    "next_action": 0,
    "metrics": {
        "reward": 1.0
    }
}

**Comment by MisterTea** [comment]
Possible actions is a binary mask. The config json has the list of actions ["0","1"] so a [1,1] means that both "0" and "1" are possible. 

Note that because gym always allows all actions, the possible actions will all be a one-vector

**Comment by martin-benson** [comment]
OK, thanks. I've gone back through the preprocessing scripts to see where the lists are converted to masks, but I still can't spot it! Could you point me to the relevant bit of the code please so that I can understand it better? Thanks!

**Comment by MisterTea** [comment]
Sure, it's happening here: https://github.com/facebookresearch/Horizon/blob/master/preprocessing/src/main/scala/com/facebook/spark/rl/Query.scala#L37

**Comment by martin-benson** [comment]
Ah! Got it! Thanks for the quick response!
