### ISSUE TITLE
how to specify categorical and continuous variables, and embeddings ?

### ISSUE THREAD

**Issue by NarasimhaM3101** [facebookresearch/Horizon#114]
How do I specify some state space variables as categorical and some as continuous? 

For example, in the network approximator (DQN or policy forward) I want to specify embedding layers for categorical variables and have them concatenated with continuous variables as Input. 

Thanks,
Narasimha

**Comment by MisterTea** [comment]
As long as the categorical variables are integers and the cardinality is low, Horizon will automatically detect them as categorical and one-hot them.

The "feature_overrides" setting in the normalization config can force some variables to be treated as continuous so they won't be quantized.

LMK if you have any other questions!

**Comment by NarasimhaM3101** [comment]
What should the max cardinality be? 

And wouldn't there be benefits by estimating embeddings as opposed to just one-hot encoding?
