### ISSUE TITLE
Issue while running "python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/discrete_dqn_cartpole_v0.json -f cartpole_discrete/training_data.json"

### ISSUE THREAD

**Issue by Raviteja1996** [facebookresearch/Horizon#123]
Hi, I am following the Horizon usage document step by step. When ever I am running the command "python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/discrete_dqn_cartpole_v0.json -f cartpole_discrete/training_data.json" I am getting the below error. I am running this in ppc64le. Please correct me if i am doing anything wrong.
Platform: ppc64le
Python version: 3.6
CUDA/cudnn:10.0/7.4

For some of the dependencies in the requirements.txt, versions mentioned are not available for ppc64le, so I installed some higher version for them like,
tensorflow : 1.13.1
thrift : 0.11.0
thrift-cpp: 0.11.0
tensorboard: 1.13.0
OpenJDK: 8.0.212

**Error:**
Traceback (most recent call last):
  File "ml/rl/test/gym/run_gym.py", line 18, in <module>
    from ml.rl.preprocessing.normalization import get_num_output_features
  File "/home/teja/Horizon/ml/rl/preprocessing/normalization.py", line 14, in <module>
    from ml.rl.thrift.core.ttypes import NormalizationParameters
  File "/home/teja/Horizon/ml/rl/thrift/core/ttypes.py", line 2007, in <module>
    class SACModelParameters(object):
  File "/home/teja/Horizon/ml/rl/thrift/core/ttypes.py", line 2023, in SACModelParameters
    }), training=SACTrainingParameters(**{
  File "/home/teja/Horizon/ml/rl/thrift/core/ttypes.py", line 1878, in __init__
    if q_network_optimizer is self.thrift_spec[2][4]:
AttributeError: 'SACTrainingParameters' object has no attribute 'thrift_spec'

**Comment by MisterTea** [comment]
This is a known issue in thrift. Downgrading to 0.10 fixes it.

**Comment by Raviteja1996** [comment]
Yeah , but as I told u I am using ppc64le I am not able to find 0.10 version thrift.

**Comment by Raviteja1996** [comment]
Is there any other way to overcome this problem?

**Comment by MisterTea** [comment]
You can build thrift 0.10 from source, or you can convince the thrift team to fix  https://issues.apache.org/jira/browse/THRIFT-4623

**Comment by Raviteja1996** [comment]
Hi I installed the thrift=0.10.0 version, but when I am trying to run the same command:**python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/discrete_dqn_cartpole_v0.json -f cartpole_discrete/training_data.json** I am getting the following error,

Error : 
Traceback (most recent call last):
  File "ml/rl/test/gym/run_gym.py", line 18, in <module>
    from ml.rl.preprocessing.normalization import get_num_output_features
  File "/home/teja/Horizon/ml/rl/preprocessing/normalization.py", line 14, in <module>
    from ml.rl.thrift.core.ttypes import NormalizationParameters
  File "/home/teja/Horizon/ml/rl/thrift/core/ttypes.py", line 11, in <module>
    from thrift.TRecursive import fix_spec
ModuleNotFoundError: No module named 'thrift.TRecursive'

**Comment by MisterTea** [comment]
Hey!  Once you change thrift, you need to rerun the thrift command before running python

**Comment by Raviteja1996** [comment]
Yeah I tried doing it from the first....but still I am facing the same problem

**Comment by MisterTea** [comment]
Hmm. Can you try deleting the files in ml/rl/thrift before running the thrift command?

**Comment by Raviteja1996** [comment]
Do you mean except the core.thrift file the remaining ones?? Because while we are running the thrift command that file is needed right.
You mean the following thrift command only right, command : thrift --gen py --out . ml/rl/thrift/core.thrift

**Comment by MisterTea** [comment]
Right, don't delete the actual .thrift files but delete the python

**Comment by Raviteja1996** [comment]
Still getting the same problem :(

**Comment by MisterTea** [comment]
Sorry, I don't know what to tell you.  Maybe make sure that the python thrift library is also 0.10?
