### ISSUE TITLE
Issue with "head -n1 cartpole_discrete_training/part*"

### ISSUE THREAD

**Issue by Raviteja1996** [facebookresearch/Horizon#124]
Hi, as I was not able to use Horizon on ppc64le, I shifted to ubuntu. I was able to install it well. And later I am following the usage page, all are going fine but when I reached the **head -n1 cartpole_discrete_training/part*** step its showing **head: cannot open 'cartpole_discrete_training/part*' for reading: No such file or directory**. Its showing same for **head -n1 cartpole_discrete_eval/part*** also. Please tell me if I am doing anything wrong. I am going as per the steps in the document.

Platform: Ubuntu 18
Python version: 3.6
CUDA/cudnn:10.0/7.4

**Comment by MisterTea** [comment]
@Raviteja1996 Can you run ".jenkins/build.sh" and paste the output?

**Comment by Raviteja1996** [comment]
**Command :** bash .jenkins/build.sh. I am running this command in the Horizon directory.
**Error log : **

[Error_log.txt](https://github.com/facebookresearch/Horizon/files/3133821/Error_log.txt)

**Comment by Raviteja1996** [comment]
I got it solved. We will do the wget for spark 2.3.3 right. So while executing this command **/usr/local/spark/bin/spark-submit \
  --class com.facebook.spark.rl.Preprocessor preprocessing/target/rl-preprocessing-1.1.jar \
  "`cat ml/rl/workflow/sample_configs/discrete_action/timeline.json`"**, I changed the spark path in the first line of the command it started working.
