### ISSUE TITLE
What does the actions listed in sample configs means?

### ISSUE THREAD

**Issue by agupta83** [facebookresearch/Horizon#125]
Hi,

In parameter file [dqn_example.json#L17-L20](https://github.com/facebookresearch/Horizon/blob/master/ml/rl/workflow/sample_configs/discrete_action/dqn_example.json#L17-L20) to train DQN model, the actions are 
```
"actions": [
    "4",
    "5"
  ],
```
What does it mean given cartpole-v0 has only two actions `{0, 1}`?

Thanks

**Comment by agupta83** [comment]
@MisterTea Any info or suggestion will be very helpful. I tried to print details during evaluation and I still have can't figure it out
```
Float State Features = [{'0': 0.16316721, '1': 1.7206059, '2': -0.22225317, '3': -2.8040316}]
Prediction: [{'4': -1.6168417, '5': 0.6317559}]
Max Q values = 5
Action Index = 1
```

My guess so far is that `actions` values from `dqn_example.json` is mapped as
```{'4': 0, '5': 1}```

Thanks

**Comment by MisterTea** [comment]
Hey!  The actions are integers starting where the state integers leave off. In this case, the state features are 0...4

The action feature IDs and state feature IDs can't overlap, which is why the actions are not 0 and 1

**Comment by agupta83** [comment]
Thank you so much @MisterTea.
