### ISSUE TITLE
what's Parametric-Action DQN??

### ISSUE THREAD

**Issue by yyuli** [facebookresearch/Horizon#129]
is there any connection between Parametric-Action DQN and this papaer's ddpg model https://arxiv.org/abs/1511.04143?

**Comment by econti** [comment]
Hey @yyuli - parametric DQN was put together by us to address domains where there are a large number of discrete actions to take that can be described by a set of features (ranking content is an example of this).

We go into more detail how it works in section 5.2 of our paper:
https://arxiv.org/pdf/1811.00260.pdf

Let me know if you have further questions.
