### ISSUE TITLE
mdp_id unicode issue

### ISSUE THREAD

**Issue by cioc** [facebookresearch/Horizon#63]
Was using str(uuid.uuid4()) for mdp_id and training model fails on call to digest.  Solved my making all mdp_id simply numeric codes.

**Comment by kittipatv** [comment]
mdp_id should take any string. Could you post stack trace?

**Comment by MisterTea** [comment]
Agree with @kittipatv , mdp_id should work with any string (although maybe you are trying to run under python2?).  Feel free to ping us and we can re-open.
