### ISSUE TITLE
tableSample explanation 

### ISSUE THREAD

**Issue by cioc** [facebookresearch/Horizon#64]
Wondering what tableSample means from the configs?  Seems important.  

https://github.com/facebookresearch/Horizon/blob/e3abf433f8bbeca3140e1a5422568a778b9a3887/preprocessing/src/main/scala/com/facebook/spark/rl/Preprocessor.scala#L13

**Comment by econti** [comment]
It defines what % of the training data should be used during training. A random sample will be grabbed based on that #.
