### ISSUE TITLE
Documentation of how optimisation of DQN happens with counterfactual policy evaluation

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/Horizon#68]

**Comment by econti** [comment]
Hey @shamanez - do you mind being a bit more specific in which parts you'd like more info on?

**Comment by chtran** [comment]
It would be good to have more documentation around how counterfactual policy evaluation works. A Google search on this didn't yield any related result

**Comment by shamanez** [comment]
@econti  In the white paper, they have mentioned merging counterfactual policy evaluation(CPE) to merged with DRL algorithms to perform stable policy updates. The main reason for this is the agent's training run on top of the real world rather than in a simulator. So there won't be immediate rewards.  So I think it is better there is good documentation about how CPE works with DRL algorithms.

**Comment by chanansh** [comment]
agreed. i also would like to know more about CPE.

**Comment by econti** [comment]
Hi all - we are working on improving our CPE methods and documentation, but for now here is some info.

We have implemented a few different CPE methods which are found in `Horizon/ml/rl/evaluation/`. Each method has a corresponding comment in the code which links to the paper which it is based off of. For example, see the [doubly robust estimator code](https://github.com/facebookresearch/Horizon/blob/master/ml/rl/evaluation/doubly_robust_estimator.py#L30).

**Comment by econti** [comment]
We also go into the CPE in more detail in our paper found here:
https://arxiv.org/abs/1811.00260
