### ISSUE TITLE
[docs] location of `requirements.txt` file isn't specified

### ISSUE THREAD

**Issue by gforsyth** [facebookresearch/Horizon#69]
Small nitpick that tripped up a colleague for a bit -- the install instructions specify to `cd Horizon` and then

```
conda install `cat requirements.txt`
```

but the req file is located in the `docker/` directory.

**Comment by ajitesh18** [comment]
I have installed dependencies from docker directory and end up having compiler issue while installing onnx -

CMake Error at /root/anaconda3/share/cmake-3.12/Modules/CMakeTestCCompiler.cmake:52 (message):
      The C compiler

        "/root/anaconda3/bin/cc"

      is not able to compile a simple test program.

Upon further analysis, found out libraries are not getting loaded properly during compile process -

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /root/anaconda3/bin/cc
Build flags:
Id flags:

The output was:
1
/usr/bin/ld: cannot find -lgcc_s

Any suggestions to resolve this issue ?

**Comment by MisterTea** [comment]
@ajitesh18 What OS?

**Comment by MisterTea** [comment]
@ajitesh18 Please file an issue with the onnx team and link it to this one, thanks

**Comment by ajitesh18** [comment]
@MisterTea Thank you. I have made a fresh installation on a different machine with same config and able to install Horizon without any issue.

**Comment by MisterTea** [comment]
Cool!
