### ISSUE TITLE
Is the log max value "2.0" correct?

### ISSUE THREAD

**Issue by kekmodel** [facebookresearch/Horizon#72]
https://github.com/facebookresearch/Horizon/blob/7f9f8d4fbd1ab0073c4953d247b5d7cd09fe63b7/ml/rl/models/actor.py#L94
Is not 20.0?

**Comment by MisterTea** [comment]
That's correct: it's the log min/max so it shouldn't be symmetrical.  putting 20 would make at most e^20 noise which is way too much noise.
