### ISSUE TITLE
low average reward for cartpole v0 example?

### ISSUE THREAD

**Issue by ghaccount** [facebookresearch/Horizon#73]
I am following the cartpole_discrete example and got  score 9.23. 
INFO:__main__:Achieved an average reward score of 9.23 over 100 evaluations.

Note: I am using the discrete_dqn_cartpole_v0.json, not the 100 eps file for training data. More data didn't help.

Its no way close to 195 expected to "solve. Could anyone comment to resolve this?

PS:CartPole-v0 defines "solving" as getting average reward of 195.0 over 100 consecutive trials.

**Comment by econti** [comment]
Hey - we found training offline on Cartpole was a bit unstable when we used a network with preprocessing. Could you try to disable the preprocessing and see if that fixes it?

**Comment by mlaicode** [comment]
Thanks @econti - you are right. Seems the network was unstable. I was able to get higher reward - got 300+ average on v0. 
BTW: I understood v0 was max 200 per episode - you can close this one as that would be a followup gym issue.

**Comment by ghaccount** [comment]
Thanks @econti. You are right. The network seems unstable. I was able to get higher 300+ reward. Closing this.

**Comment by sdegeusmob** [comment]
Hey,
I also get bad results for training offline on Cartpole. How would I disable the preprocessing?
