### ISSUE TITLE
Unit tests not utilizing GPU

### ISSUE THREAD

**Issue by robwebbjr** [facebookresearch/Horizon#75]
First time posting an issue; please pardon any improprieties....

The post install tests returned OK (with 1 skipped), but the tests don't appear to be using the GPU, as these lines appear repeatedly throughout the tests:

INFO:ml.rl.preprocessing.preprocessor:CUDA availability: True
INFO:ml.rl.preprocessing.preprocessor:NOT Using GPU: GPU not requested or not available.

Is this normal?

How might I verify that Horizon is properly configured to make use of the GPU?

Pytorch does see the GPU:

>>> import torch
>>> torch.cuda.current_device()
0
>>> torch.cuda.device(0)
<torch.cuda.device object at 0x7f2a806edfd0>
>>> torch.cuda.device_count()
1
>>> torch.cuda.get_device_name(0)
'GeForce GTX 1060 with Max-Q Design'
>>> torch.cuda.is_available()
True

I'm using a Dell G7 with Ubuntu 18.04.1

Thanks.

**Comment by MisterTea** [comment]
If you only skipped 1 test, then many of the tests are using the GPU and passing.

Some of the tests run on CPU mode on purpose.  These tests will not use the GPU and generate that message.

As long as your training config has use_gpu set to true, you will use the GPU.

**Comment by robwebbjr** [comment]
Thank you for responding.
Noob question:
Please tell me where precisely to check for 
use_gpu set to true
?
Thanks!

**Comment by MisterTea** [comment]
Yep, you need to specify a json config when training a model (see the tutorial for details).  Here's where use_gpu is set: https://github.com/facebookresearch/Horizon/blob/master/ml/rl/workflow/sample_configs/discrete_action/dqn_example.json#L5

**Comment by robwebbjr** [comment]
Great!
Thank you so much!
