### ISSUE TITLE
`next_action` key does not exist in timeline data

### ISSUE THREAD

**Issue by baek-jinoo** [facebookresearch/Horizon#82]
While following the doc [usage](https://github.com/facebookresearch/Horizon/blob/master/docs/usage.md), I found that the data generated by running `python ml/rl/test/gym/run_gym.py -p ml/rl/test/gym/discrete_dqn_cartpole_v0_100_eps.json -f cartpole_discrete/training_data.json` and the subsequent commands does not generate `next_action`, thus, generating this error when running `python ml/rl/workflow/dqn_workflow.py -p ml/rl/workflow/sample_configs/discrete_action/dqn_example.json`

```
root@66f0303019f9:~/Horizon# python ml/rl/workflow/dqn_workflow.py -p ml/rl/workflow/sample_configs/discrete_action/dqn_example.json
Traceback (most recent call last):
  File "ml/rl/workflow/dqn_workflow.py", line 164, in <module>
    train_network(params)
  File "ml/rl/workflow/dqn_workflow.py", line 121, in train_network
    tdp = preprocess_batch_for_training(preprocessor, batch, action_names)
  File "/home/Horizon/ml/rl/workflow/training_data_reader.py", line 234, in preprocess_batch_for_training
    next_actions = read_actions(action_names, batch["next_action"])
```

I got it to work with the gz files. It was a bit confusing that one of the suggested ways didn't work.

**Comment by MisterTea** [comment]
Hey @baek-jinoo, this should be fixed now.  Can you verify?

**Comment by baek-jinoo** [comment]
I followed these steps to generate the data from my machine. https://github.com/facebookresearch/Horizon/blob/master/docs/usage.md

I was trying it with new `master`

and I'm hitting these issues:

```
root@5742eccf7dcd:~/Horizon# python ml/rl/workflow/create_normalization_metadata.py -p ml/rl/workflow/sample_configs/discrete_action/dqn_example.json
INFO:__main__:Generating norm table based on training_data/cartpole_discrete_timeline.json
Traceback (most recent call last):
  File "ml/rl/workflow/create_normalization_metadata.py", line 105, in <module>
    create_norm_table(params)
  File "ml/rl/workflow/create_normalization_metadata.py", line 35, in create_norm_table
    params["training_data_path"], batch_size=NORMALIZATION_BATCH_READ_SIZE
  File "/home/Horizon/ml/rl/workflow/training_data_reader.py", line 24, in __init__
    self.len = self.line_count()
  File "/home/Horizon/ml/rl/workflow/training_data_reader.py", line 63, in line_count
    with open(self.path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'training_data/cartpole_discrete_timeline.json'
```

This happens when after I do `mv cartpole_discrete_training/part*  training_data/cartpole_training_data.json`. So, then, I tried `mv cartpole_discrete_training/part*  training_data/cartpole_discrete_timeline.json` instead and it worked (unsure if that's appropriate though). 

Also, then, I hit an issue where building the model fails when I do not have the eval data setup as well like such:

```
root@4c565b7f64bb:~/Horizon# python ml/rl/workflow/dqn_workflow.py -p ml/rl/workflow/sample_configs/discrete_action/dqn_example.json
Traceback (most recent call last):
  File "ml/rl/workflow/dqn_workflow.py", line 149, in <module>
    train_network(params)
  File "ml/rl/workflow/dqn_workflow.py", line 69, in train_network
    eval_dataset = JSONDataset(params["eval_data_path"], batch_size=16)
  File "/home/Horizon/ml/rl/workflow/training_data_reader.py", line 24, in __init__
    self.len = self.line_count()
  File "/home/Horizon/ml/rl/workflow/training_data_reader.py", line 63, in line_count
    with open(self.path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'training_data/cartpole_discrete_timeline_eval.json'
```

So, this seems to work when I also do `mv cartpole_discrete_eval/part* training_data/cartpole_discrete_timeline_eval.json` before I run the normalization step.

I get to train the model and create the output for eval. But, my outputs do not successfully show plots on tensorboard. (When I did it with the gz output, it showed the plots)  ![image](https://user-images.githubusercontent.com/7891365/50381214-0ac20980-0636-11e9-9004-bfaa191a67b6.png)
[outputs.zip](https://github.com/facebookresearch/Horizon/files/2705772/outputs.zip)



FYI, I ran the sim and training on a linux machine with GPU and then moved over the outputs and ran tensorboard within a conda env that has 
```
Horizon $ cat docker/requirements.txt
numpy==1.15.1
pandas==0.23.4
protobuf==3.6.1
pytest-xdist==1.24.0
scipy==1.1.0
tensorboard==1.9.0
tensorboardX==1.4
tensorflow==1.9.0
thrift==0.10.0
thrift-cpp==0.10.0
```

**Comment by baek-jinoo** [comment]
After the update to the usages doc in https://github.com/facebookresearch/Horizon/commit/30c75bed0e328e18bfc324f010101fac930c3abc I see this:

![image](https://user-images.githubusercontent.com/7891365/52042239-82b30780-24f1-11e9-9c4a-4effa674363a.png)

I think it looks good.
