### ISSUE TITLE
More supported models?

### ISSUE THREAD

**Issue by JunchenJin** [facebookresearch/Horizon#84]
Dear authors,

Great work for the excellent. Below are the lists of supported models, which we think some other more methods are also crucial for some applications. 
Discrete-Action DQN
Parametric-Action DQN
Double DQN, Dueling DQN, Dueling Double DQN
DDPG (DDPG)
Soft Actor-Critic (SAC)

Do have plans to implement some other deep RL models and include in this framework, such as (Async) Advantage Actor-Critic (A3C / A2C), Continuous A3C, and Distributed Deep Deterministic Policy Gradient (Distributed DDPG, aka D3PG), Parallelized Proximal Policy Optimization (P3O, similar to DPPO), etc.?

We plan to work on other more deep RL models using your framework, and hopefully, it is not a redundant work if you already plan to do so. 

Thanks!

**Comment by MisterTea** [comment]
@JunchenJin Hey!  We don't plan on adding those models anytime soon.  The current plan is to improve the tooling, documentation, etc..  We may add new model architectures such as probabilistic neural nets, bayesian neural nets, etc..  If you add any of those models, submit a PR! :-D

**Comment by dcompgriff** [comment]
Piggy backing off of this, are there any plans for incorporating more sample efficient methods?

**Comment by MisterTea** [comment]
@dcompgriff We are working on Bayesian DQN and some model-based methods :-D
