### ISSUE TITLE
Tensorboard not showing any data

### ISSUE THREAD

**Issue by vidhandosi** [facebookresearch/Horizon#85]
Hi Team,

I have done all the installation in the Docker container. I run the command provided in the usage document and when running on Tensorboard it didn't display any image, histogram, scalar, audio.
Please see below images  
![tensorboard-1](https://user-images.githubusercontent.com/15984446/50588598-ddccec80-0ea8-11e9-8a25-03cb18474763.png)
![tensorboard-2](https://user-images.githubusercontent.com/15984446/50588642-00f79c00-0ea9-11e9-9fc2-ef2575ee3834.png)

Please help me to resolve this issue.
Thanks in Advance.

**Comment by MisterTea** [comment]
Fixed by https://github.com/facebookresearch/Horizon/commit/90597cd8f5daf64f217138ef745b9853f0409e34 .  Please let me know if you still see this issue.
