### ISSUE TITLE
Max being computed for wrong q values

### ISSUE THREAD

**Issue by nikhilsaldanha** [facebookresearch/Horizon#88]
In [dqn_trainer_base.py](https://github.com/facebookresearch/Horizon/blob/master/ml/rl/training/dqn_trainer_base.py), the method [get_max_q_values_with_target()](https://github.com/facebookresearch/Horizon/blob/master/ml/rl/training/dqn_trainer_base.py#L34) is returning the max of Q values from the current network instead of the max of Q values from the target network.

According to the Q learning Update equation: Loss = R + gamma . [max a' Q(s', a'; **target**)] - Q(s, a; current)

But according to the implementation in dqn_trainer_base.py, this is happening:
Loss = R + gamma . [max a' Q(s', a'; **current**)] - Q(s, a; current)

**Comment by MisterTea** [comment]
Thanks for the catch!  I recently refactored this code and broke that.  To be clear: it does the right thing if you have double-q learning, but without that it is using the current network.  I'll have a commit out soon.

**Comment by MisterTea** [comment]
Fixed by https://github.com/facebookresearch/Horizon/commit/d4d9752dab72418c47eef770014dc950a9fd2b3c
