### ISSUE TITLE
What is the interpretation of these numbers?

### ISSUE THREAD

**Issue by rezanazari** [facebookresearch/Horizon#89]
After running the CPE for CartPole-v0, it gives the following output:

Reward Inverse Propensity Score : normalized 0.500 raw 0.500
Reward Direct Method : normalized 1.000 raw 1.000
Reward Doubly Robust P.E. : normalized 0.999 raw 0.999
Value Weighted Doubly Robust P.E. : normalized 12163.311 raw 1026487.620
Value Sequential Doubly Robust P.E. : normalized 2128.063 raw 179591.880
Value Magic Doubly Robust P.E. : normalized 4535.132 raw 382729.374

I am wondering what are these numbers? I think that they should be ideally close to 200, but they are off a little bit. Thanks.

**Comment by MisterTea** [comment]
Hey @rezanazari , thanks for letting us know.  The inverse propensity score number looks strange.  It may be a logging issue in the open source workflow.  We're taking a look, thanks!

**Comment by MisterTea** [comment]
The docs are updated and tensorboard has been fixed.
