### ISSUE TITLE
cuda.DockerfileSpark : ONNX installation error and spark download URL

### ISSUE THREAD

**Issue by krunalpuri** [facebookresearch/Horizon#90]
`docker build -f cuda.Dockerfile -t horizon:dev .`

While try to build cuda.Dockerfile, it throws an error at 

> Step 16/29 : RUN pip install onnx
> ....

> ....
> ....
> Building wheels for collected packages: onnx
>   Running setup.py bdist_wheel for onnx: started
>   Running setup.py bdist_wheel for onnx: finished with status 'error'
>   Complete output from command /home/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-368dwgq1/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-a73n9mvb --python-tag cp36:
>   fatal: not a git repository (or any of the parent directories): .git
> ....

> Failed building wheel for onnx
> ....

> Command "/home/miniconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-368dwgq1/onnx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-e2laxxau/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-368dwgq1/onnx/
> The command '/bin/bash -c pip install onnx' returned a non-zero code: 1
> 

And the second issue:

https://github.com/facebookresearch/Horizon/blob/810b89f31204eabe54b354bd7e828d0918ed46c1/docker/cuda.Dockerfile#L66

The URL does not work any more.

**Comment by kittipatv** [comment]
@krunalpuri we have update the docker files to install newer version of Spark. ONNX installation issue should be coming from upstream. It most likely fixed now. Let us know if you still have issues installing.

**Comment by kittipatv** [comment]
Please reopen if this is still broken in master
